when:
  event: [tag]

steps:
  publish:
    image: woodpeckerci/plugin-docker-buildx
    settings:
      platforms: linux/amd64
      repo: codeberg.org/${CI_REPO,,}
      registry: codeberg.org
      tags: ${CI_COMMIT_TAG}
      username: ${CI_REPO_OWNER}

      password:
        from_secret: ci_token
