name: BuildOnTag

on: [create]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "6.0"
      - name: Restore local tools
        run: dotnet tool restore
      - name: Docker login
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login docker.pkg.github.com --username ${{ github.actor }} --password-stdin
      - name: Run FAKE build
        env:
          USERNAME: ${{ github.actor }}
        run: dotnet fake build -t PushContainer
      - name: Docker logout
        run: docker logout
