name: BuildOnTag

on: [create]

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.0.100'
    - name: Restore local tools
      run: dotnet tool restore
    - name: Docker login
      run: docker login docker.pkg.github.com --username ${{ github.actor }}
    - name: Run FAKE build
      env:
        USERNAME: ${{ github.actor }}
      run: dotnet fake build -t PushContainer
    - name: Docker logout
      run: docker logout
