name: BuildOnTag

on: [create]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "7.0"
      - name: Dotnet add nuget source
        run: dotnet nuget add source https://www.myget.org/F/secret-feed-lamp/api/v3/index.json
      - name: Dotnet build
        run: dotnet build -c Release -o Release
      - name: Docker login
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login docker.pkg.github.com --username ${{ github.actor }} --password-stdin
      - name: Set Version
        run: echo "VERSION=$(head -n 1 release-notes.md | cut -d' ' -f 2)" >> $GITHUB_ENV
      - name: Build container
        run: docker build . -t docker.pkg.github.com/${{ github.actor }}/hashsethomepage/hashset:${{ env.VERSION }}
      - name: Push container
        env:
          USERNAME: ${{ github.actor }}
        run: dotnet fake build -t PushContainer
      - name: Docker logout
        run: docker logout
