name: BuildOnTag

on: [create]

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.0.100'
    - name: Test
      run: cat $HOME/runner/.docker/config.json
    - name: Restore local tools
      run: dotnet tool restore
    - name: Docker login
      env:
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: echo "$DOCKER_PASSWORD" | docker login --username ${{ github.actor }} --password-stdin
    - name: Run FAKE build
      env:
        username: ${{ github.actor }}
      run: dotnet fake build
