name: BuildOnTag

on: [ create ]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "7.0"
      - name: Dotnet tool restore
        run: dotnet tool restore
      - name: Generate Hydra files
        working-directory: ./src/App
        env:
          HASHSET_CONNECTION_STRING: ${{ secrets.HASHSET_CONNECTION_STRING }}
        run: dotnet sqlhydra npgsql --connection-string "$HASHSET_CONNECTION_STRING"
      - name: Dotnet build
        run: dotnet build -c Release -o Release
      - name: Docker login
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login docker.pkg.github.com --username ${{ github.actor }} --password-stdin
      - name: Set Version
        run: echo "VERSION=$(head -n 1 release-notes.md | cut -d' ' -f 2)" >> $GITHUB_ENV
      - name: Build container
        run: docker build . -t docker.pkg.github.com/${{ github.actor }}/hashsethomepage/hashset:${{ env.VERSION }}
      - name: Push container
        env:
          USERNAME: ${{ github.actor }}
        run: docker push docker.pkg.github.com/${{ github.actor }}/hashsethomepage/hashset:${{ env.VERSION }}
      - name: Docker logout
        run: docker logout
